version: '3.9'
services:
  mariadb:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: piskvorky_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  server:
    container_name: server
    build: ./server
    ports:
      - '9090:9090'
    environment:
      TTT_DB: piskvorky_db
      TTT_DB_ADDRESS: mariadb
      TTT_DB_USER: root
      TTT_DB_PASSWORD: password
      TTT_DB_PORT: 3306

  web:
    container_name: web
    build: ./web
    ports:
      - '80:80'
    environment:
      NGINX_PORT: 80
