POST http://localhost:9090/v1/login
Content-Type: application/json

{"email":  "admin@admin.com", "password": "pass123"}

###
POST http://localhost:9090/v1/register
Content-Type: application/json

{"email":  "admin@admin.com", "password": "pass123"}

###
POST http://localhost:9090/v1/lost-passwd
Content-Type: application/json

{"email":  "admin@admin.com"}

###
GET http://localhost:9090/v1/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6ImxvY2FsaG9zdCIsImFkbWluIjpmYWxzZSwiaWQiOjEsImV4cCI6MTYwOTAzNTAzOSwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20ifQ.vwYHMXsPvcs5LOOMZmMSRujPjE2J0LcpAP-VSsbz_4uKgHJO1iZr24HyfZLaXRbCd9QCQlKXFURcKWYXNS7oeQ

###
POST http://localhost:9090/v1/profile/change-passwd
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6ImxvY2FsaG9zdCIsImlkIjoxLCJleHAiOjE2MDg5NjAyNjQsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIn0.7COr67Ekreu8oKSG1EBVzrhplTTnzMVi1Gxc3J06H796Wrw0qQcjXMP8pcUNShe2gcOgXQznmzRa7OLbvZ0lrw

{"email":  "admin@admin.com", "password": "pass123", "passwordCurrent": "pass124" }

###
GET http://localhost:9090/hello


###
GET http://localhost:9090/v1/admin
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6ImxvY2FsaG9zdCIsImFkbWluIjp0cnVlLCJpZCI6MSwiZXhwIjoxNjA5MDM1MzU3LCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSJ9.95ca9rOVp_sFiHMptDuI1uvQMPCTkbEUukcOXGgTpkXQltjanfphP8oLlaaTKP3WOQ_gMMQ9-mLtXqeK0wCnfg
