POST http://localhost:9090/v1/login
Content-Type: application/json

{"email":  "admin@admin.com", "password": "pass123"}

###
GET http://localhost:9090/v1/profile
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6ImxvY2FsaG9zdCIsImlkIjoxLCJleHAiOjE2MDg4NDk3NDEsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIn0.UyRXateFxpmeMLGOLyWP36m_rFXtdAfiQ7WeGaKvCxtoYbhpbYXPtf5ZZR6nbEQAJKzFK45TpmVtwWw2EtKUwA

###
GET http://localhost:9090/v1/game
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6ImxvY2FsaG9zdCIsImlkIjoxLCJleHAiOjE2MDg4NDM5NDgsImVtYWlsIjoiYWRtaW5AYWRtaW4uY29tIn0.Vj_0QhRi315dF1tKFVpf5QcX53Uuocwh6A5nvIU9uvlYVRWoJpBJBZidrJR36RVLeRg2BtBk_41WQTLHbV3oIQ

###
GET http://localhost:9090/hello


###
GET http://localhost:8080/