/**
* Piskvorky API
* Piskvorky app server REST API specification
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
* 
* Values: none,cross,nought
*/
@Serializable(with = BoardValue.Serializer::class)
enum class BoardValue(val value: kotlin.String){


    none("none"),


    cross("cross"),


    nought("nought");



    /**
    This override toString avoids using the enum var name and uses the actual api value instead.
    In cases the var name and value are different, the client would send incorrect enums to the server.
    **/
    override fun toString(): String {
        return value
    }

    object Serializer : CommonEnumSerializer<BoardValue>("BoardValue", values(), values().map { it.value.toString() }.toTypedArray())
}

