/**
* Piskvorky API
* Piskvorky app server REST API specification
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param id 
 * @param email 
 * @param online 
 * @param inGame 
 */
@Serializable
data class Friend (
    @SerialName(value = "id") val id: kotlin.Int? = null,
    @SerialName(value = "email") val email: kotlin.String? = null,
    @SerialName(value = "online") val online: kotlin.Boolean? = null,
    @SerialName(value = "inGame") val inGame: kotlin.Boolean? = null
)

