/**
* Piskvorky API
* Piskvorky app server REST API specification
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model

import cz.martinforejt.piskvorky.api.model.Friend

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param friends 
 */
@Serializable
data class FriendsListResponse (
    @SerialName(value = "friends") @Required val friends: kotlin.collections.List<Friend>
)

