/**
* Piskvorky API
* Piskvorky app server REST API specification
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param userId 
 * @param email 
 * @param created 
 */
@Serializable
data class FriendRequest (
    @SerialName(value = "userId") val userId: kotlin.Int? = null,
    @SerialName(value = "email") val email: kotlin.Int? = null,
    @SerialName(value = "created") val created: kotlin.String? = null
)

