/**
* Piskvorky API
* Piskvorky app server REST API specification
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model

import cz.martinforejt.piskvorky.api.model.Board
import cz.martinforejt.piskvorky.api.model.BoardValue
import cz.martinforejt.piskvorky.api.model.Player

import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param status 
 * @param board 
 * @param cross 
 * @param nought 
 * @param current 
 * @param winner 
 */
@Serializable
data class GameSnap (
    @SerialName(value = "status") @Required val status: GameSnap.Status,
    @SerialName(value = "board") @Required val board: Board,
    @SerialName(value = "cross") @Required val cross: Player,
    @SerialName(value = "nought") @Required val nought: Player,
    @SerialName(value = "current") @Required val current: BoardValue,
    @SerialName(value = "winner") @Required val winner: BoardValue
) {

    /**
    * 
    * Values: running,end
    */
    @Serializable(with = Status.Serializer::class)
    enum class Status(val value: kotlin.String){
        running("running"),
        end("end");

        object Serializer : CommonEnumSerializer<Status>("Status", values(), values().map { it.value.toString() }.toTypedArray())
    }
}

