/**
* Piskvorky API
* Piskvorky app server REST API specification
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model


import kotlinx.serialization.*
import kotlinx.serialization.internal.CommonEnumSerializer

/**
 * 
 * @param id 
 * @param email 
 * @param cross 
 */
@Serializable
data class Player (
    @SerialName(value = "id") @Required val id: kotlin.Int,
    @SerialName(value = "email") @Required val email: kotlin.String,
    @SerialName(value = "cross") @Required val cross: kotlin.Boolean
)

