/**
* User Service contract
* This is a sample specification for user service
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package cz.martinforejt.piskvorky.api.model


import kotlinx.serialization.*

/**
 * 
 * @param name 
 */
@Serializable
data class UserCreateRequest (
    @SerialName(value = "name") val name: kotlin.String? = null
)

