openapi: "3.0.0"
info:
  version: v1
  title: Piskvorky API
  description: "Piskvorky app server REST API specification"
servers:
  - url: http://localhost:9090/v1
  - url: https://localhost:9090/v1
paths:

  /login:
    post:
      summary: Login user
      tags:
        - security
      security: []
      requestBody:
        description: Provide email and password
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: JWT token and validity (in ms)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /register:
    post:
      summary: Register user
      tags:
        - security
      security: []
      requestBody:
        description: Provide email and password
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        '200':
          description: Register succes, auto login - JWT token and validity (in ms)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /lost-passwd:
    post:
      summary: Request to send new password to email
      tags:
        - security
      security: []
      requestBody:
        description: Email to send new passoword
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LostPasswordRequest"
      responses:
        '200':
          description: Sent
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /profile:
    get:
      summary: Logged user profile info
      tags:
        - profile
      responses:
        '200':
          description: Profile info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfileInfo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /profile/change-passwd:
    post:
      summary: Change password
      tags:
        - profile
      requestBody:
        description: Email, new password, current password
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordRequest"
      responses:
        '200':
          description: Sent
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    LoginResponse:
      type: object
      required: [token]
      properties:
        token:
          type: string
    RegisterRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
        password:
          type: string
    LostPasswordRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
    ProfileInfo:
      type: object
      required: [email]
      properties:
        email:
          type: string
    ChangePasswordRequest:
      type: object
      required: [email, password, passwordCurrent]
      properties:
        email:
          type: string
        password:
          type: string
        passwordCurrent:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

security:
  - bearerAuth: []